### PR TITLE
Update tokens.ts

### PR DESCRIPTION
**Pull request by smies1992**
New coin

## Summary by CodeRabbit

- **New Features**
	- Added "Shinja" (INJA) token metadata, including name, symbol, logo, and CoinGecko ID details.

### CODE REVIEW

**Comment by bangjelkoski** [comment]
There is no image?

**Comment by smies1992** [comment]
I'm sorry. I thought it was included



[image: 31e40d5d-d68a-45ce-bbac-965cebe1e8ac.png]



Op di 19 mrt 2024 om 15:25 schreef Bojan Angjelkoski <
***@***.***>:

**Comment by bangjelkoski** [comment]
It's still not included in the PR.

**Comment by smies1992** [comment]
ShibaNinja

**Pull request closed without merging**
