### PR TITLE
feat: integrate FoxWallet

### PR DESCRIPTION
**Pull request by ljunb**
Hello, we are the FoxWallet team, we hope to add FoxWalelt strategy to `wallet-ts`, you can learn more about our team at [here](https://foxwallet.com/).

This pull request includes the following features:
1. Support enabling users to interact with Cosmos-based chains directly from the app
2. Support getting account addresses, signing transactions, and sending transactions
3. Note: Currently only Cosmos addresses are supported, Ethereum addresses are not yet supported

## Summary by CodeRabbit

- **New Features**
	- Introduced support for `FoxWallet`, allowing users to create and manage this new wallet type.
	- Added enhanced wallet management capabilities for `FoxWallet` with transaction signing and broadcasting features.

- **Bug Fixes**
	- Improved wallet detection and installation checks for `FoxWallet` within the Cosmos ecosystem.

- **Documentation**
	- Updated wallet strategy documentation to include details about the new `FoxWallet` functionality.

- **Chores**
	- Streamlined module imports for better code organization and maintainability.

### CODE REVIEW

**Comment by billyjacoby** [comment]
Hey, we are doing some refactors on the `wallet-ts` package and will ping you here once the refactor is done.

**Comment by billyjacoby** [comment]
Hey @ljunb  - our wallet refactor should be complete now. It looks like you were adding this as a cosmos wallet, so you should be able to add that to our new `wallet-cosmos` package. Have a look [here](https://github.com/InjectiveLabs/injective-ts/tree/dev/packages/wallets/wallet-cosmos) and feel to to open a PR here and I'll be closing this one in the mean time.

**Comment by ljunb** [comment]
So if I want to use FoxWallet as a cosmos wallet, should I add it to the `wallets` directory as an independent package, such as `wallets/wallet-foxwallet`?

**Comment by billyjacoby** [comment]
Preferably in the `wallet-cosmos` package itself if it matches the same implementation as cosmos wallets and doesn't include any new dependencies. If this would require new dependencies then yeah creating a new wallet package would be the desired path. Take a look at how the `wallet-cosmos` package includes support for  Leap, Keplr, and Ninji and see if that would work for you.

**Comment by ljunb** [comment]
Forgive me forgot how I tested it before. Is there an example that can quickly test the newly added wallet?

**Comment by billyjacoby** [comment]
You can find an example of the current cosmos wallet integration [here](https://github.com/InjectiveLabs/injective-ts/tree/dev/packages/wallets/wallet-cosmos#-documentation). I would suggest to use that as a jumping off point after cloning the repo and running locally

**Comment by ljunb** [comment]
FoxWallet is a multi-chain wallet that not only supports the Cosmos ecosystem network. What do you think is the appropriate way to add it to this package😄?

**Pull request closed without merging**
