### PR TITLE
Update tokens.ts

### PR DESCRIPTION
**Pull request by KinjaToken**

### CODE REVIEW

**Comment by bangjelkoski** [comment]
Will update from local branch.

**Comment by bangjelkoski** [comment]
Why are you changing the name and the symbol?!

**Comment by cryptodev-t** [comment]
KinjaToken guy broke our INJINU token info.
Please don't accept this PR.

**Comment by bangjelkoski** [comment]
Removed entirelly.

**Comment by KinjaToken** [comment]
I haven‘t any idea how is it happen!
Sorry for that. But we would be happy if you can verified our data again too. 

Maybe there was a mistake. Best regards

**Pull request closed without merging**
