### PR TITLE
Add metadata for Waifu Token

### PR DESCRIPTION
**Pull request by mitruth**

### CODE REVIEW

**Comment by bangjelkoski** [comment]
Image too big, no blank space above the symbol key:

```
  },
  <-- blank row here
  WAIFU: {
 ```
  
 Can you guys at least try what others are doing and do the same?

**Comment by mitruth** [comment]
I was trying but i got rejected 5 times and tried to do it in pieces.
Should i change the image and delete that blank space ?

**Comment by bangjelkoski** [comment]
Add a blank space and upload a new image that's lower in size

**Comment by mitruth** [comment]
I will do it. In the meantime, i cannot update the entity.json file, i get
an error at the format.sh script in the automatic verification.

Running .github/scripts/dist/yacar_ci_linux_amd64
6
<https://github.com/coinhall/yacar/actions/runs/7422598966/job/20198233341?pr=5133#step:3:7>2024/01/05
13:47:39 Sorted JSONs successfully...
7
<https://github.com/coinhall/yacar/actions/runs/7422598966/job/20198233341?pr=5133#step:3:8>2024/01/05
13:47:39 unused entity: Waifu
8
<https://github.com/coinhall/yacar/actions/runs/7422598966/job/20198233341?pr=5133#step:3:9>Error:
Process completed with exit code 1.




{
    "name": "Waifu",
    "website": "https://waifuinj.com/",
    "telegram": "https://t.me/waifuinj",
    "twitter": "https://twitter.com/WaifuINJ"
  },

this is what i am adding. Do you have any idea why this error appears ?

**Comment by bangjelkoski** [comment]
I don't know how Coinhall works.

**Comment by mitruth** [comment]
yes, my bad, i thought you were from coinhall. I did what you asked, hope
its ok now. thank you !

**Pull request closed without merging**
